# -*- coding: utf-8 -*-
"""tugas_akhir_judul1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UFhtyGnPczWDT7VSboeG5McFAuHP4olA
"""

def menu():
    print("===== MENU TOKO =====")
    print("1. Tampilkan address data barang")
    print("2. Tampilkan address setiap barang")
    print("3. Input harga barang")
    print("4. Tampilkan daftar harga")
    print("5. Keluar")


def main():
    harga_barang = [0] * 5
    running = True

    while running:
        menu()

        try:
            choice = int(input("Pilih menu: "))
        except ValueError:
            print("Input harus angka!")
            continue

        if choice == 1:
            print(f"Address list barang: {id(harga_barang)}")

        elif choice == 2:
            print("Address setiap barang:")

            for i in range(5):
                print(f"Barang ke-{i+1}: {id(harga_barang[i])}")

        elif choice == 3:
            print("Masukkan harga barang:")

            for i in range(5):
                while True:
                    try:
                        harga_barang[i] = int(input(f"Harga barang ke-{i+1}: "))
                        break
                    except ValueError:
                        print("Masukkan angka!")

            print(f"Data harga barang: {harga_barang}")

        elif choice == 4:
            print("Daftar harga barang:")

            for i in range(5):
                print(f"Barang ke-{i+1} = Rp {harga_barang[i]}")

        elif choice == 5:
            running = False
            print("Program selesai")

        else:
            print("Menu tidak tersedia")


if __name__ == "__main__":
    main()