# -*- coding: utf-8 -*-
"""tugas_akhir_judul3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rLoIOgLnX2rd8mKqBDzks0c1hY7uXcYN
"""

def sequential_search(data, n, target):
    i = 0
    counter = 0
    while i < n:
        if data[i] == target:
            counter += 1
        i += 1
    return counter


def main():
    ukuran_sepatu = [38, 40, 39, 41, 38, 42, 40, 39, 38, 41]
    n = len(ukuran_sepatu)

    print(f"Data ukuran sepatu mahasiswa: {ukuran_sepatu}")

    while True:
        try:
            target = int(input("Masukkan ukuran sepatu yang ingin dicari: "))
            break
        except ValueError:
            print("Input tidak valid, silakan masukkan angka!")

    counter = sequential_search(ukuran_sepatu, n, target)

    if counter > 0:
        print(f"Ukuran sepatu {target} ditemukan sebanyak {counter} kali.")
    else:
        print(f"Ukuran sepatu {target} tidak ditemukan.")


if __name__ == "__main__":
    main()