# -*- coding: utf-8 -*-
"""tugas_akhir_judul4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ELbDvVAlnZT3bg77ngMSPeA8sRCJh9gw
"""

class StackArray:
    def __init__(self, max_size=100):
        self.MAX = max_size
        self.st = [None] * self.MAX
        self.top_idx = -1

    def is_empty(self):
        return self.top_idx == -1   # tumpukan majalah kosong

    def is_full(self):
        return self.top_idx == self.MAX - 1   # rak majalah penuh

    def push(self, x):
        if self.is_full():
            print("Rak majalah penuh")
            return
        self.top_idx += 1
        self.st[self.top_idx] = x
        print(f"Majalah '{x}' ditaruh di atas")

    def pop(self):
        if self.is_empty():
            print("Tidak ada majalah")
            return
        print(f"Majalah '{self.st[self.top_idx]}' diambil dari atas")
        self.top_idx -= 1

    def peek(self):
        if self.is_empty():
            print("Tidak ada majalah")
            return
        print(f"Majalah paling atas: {self.st[self.top_idx]}")

    def display(self):
        if self.is_empty():
            print("Tidak ada majalah")
            return
        print("Isi tumpukan majalah (atas ke bawah): ", end="")
        for i in range(self.top_idx, -1, -1):
            print(self.st[i], end=" ")
        print()


def main():
    stack = StackArray()
    pilih = 0

    while pilih != 5:
        print("TUMPUKAN MAJALAH")
        print("1. Taruh majalah")
        print("2. Ambil majalah")
        print("3. Lihat majalah paling atas")
        print("4. Tampilkan semua majalah")
        print("5. Keluar")
        try:
            pilih = int(input("Pilih: "))
        except ValueError:
            print("Input tidak valid!")
            continue

        if pilih == 1:
            val = input("Nama majalah: ")
            stack.push(val)

        elif pilih == 2:
            stack.pop()

        elif pilih == 3:
            stack.peek()

        elif pilih == 4:
            stack.display()

        elif pilih == 5:
            print("Program selesai.")

        else:
            print("Pilihan tidak valid!")


if __name__ == "__main__":
    main()