# -*- coding: utf-8 -*-
"""tugas_akhir_judul5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FtE1oZiNqEIUwT2QqmWthPm1ovdW4eHh
"""

class Node:
    def __init__(self, nomor_meja):
        self.nomor_meja = nomor_meja
        self.left = None
        self.right = None


class BSTRestoran:
    def __init__(self):
        self.root = None

    def insert_node(self, root, nomor_meja):
        if root is None:
            return Node(nomor_meja)

        if nomor_meja < root.nomor_meja:
            root.left = self.insert_node(
                root.left,
                nomor_meja
            )

        elif nomor_meja > root.nomor_meja:
            root.right = self.insert_node(
                root.right,
                nomor_meja
            )

        return root

    def insert(self, nomor_meja):
        self.root = self.insert_node(
            self.root,
            nomor_meja
        )

    def find_min_node(self, root):
        current = root

        while current is not None and current.left is not None:
            current = current.left

        return current

    def delete_node(self, root, nomor_meja):
        if root is None:
            return None

        if nomor_meja < root.nomor_meja:
            root.left = self.delete_node(
                root.left,
                nomor_meja
            )

        elif nomor_meja > root.nomor_meja:
            root.right = self.delete_node(
                root.right,
                nomor_meja
            )

        else:
            if root.left is None and root.right is None:
                return None

            elif root.left is None:
                return root.right

            elif root.right is None:
                return root.left

            else:
                successor = self.find_min_node(
                    root.right
                )

                root.nomor_meja = (
                    successor.nomor_meja
                )

                root.right = self.delete_node(
                    root.right,
                    successor.nomor_meja
                )

        return root

    def delete(self, nomor_meja):
        self.root = self.delete_node(
            self.root,
            nomor_meja
        )

    def tampilkan_meja(self, root):
        if root is None:
            return

        self.tampilkan_meja(root.left)

        print(
            f"Meja Nomor {root.nomor_meja}"
        )

        self.tampilkan_meja(root.right)

    def jumlah_meja(self, root):
        if root is None:
            return 0

        return (
            1
            + self.jumlah_meja(root.left)
            + self.jumlah_meja(root.right)
        )

    def find_successor(self, root, nomor_meja):
        current = root
        successor = None

        while current is not None:
            if nomor_meja < current.nomor_meja:
                successor = current
                current = current.left

            elif nomor_meja > current.nomor_meja:
                current = current.right

            else:
                break

        if current is None:
            return None, False

        if current.right is not None:
            successor = self.find_min_node(
                current.right
            )

        if successor is None:
            return None, False

        return successor.nomor_meja, True

    def find_predecessor(self, root, nomor_meja):
        current = root
        predecessor = None

        while current is not None:
            if nomor_meja > current.nomor_meja:
                predecessor = current
                current = current.right

            elif nomor_meja < current.nomor_meja:
                current = current.left

            else:
                break

        if current is None:
            return None, False

        if current.left is not None:
            temp = current.left

            while temp.right is not None:
                temp = temp.right

            predecessor = temp

        if predecessor is None:
            return None, False

        return predecessor.nomor_meja, True


def main():
    bst = BSTRestoran()
    pilih = 0

    while pilih != 7:
        print("\n=== RESERVASI MEJA RESTORAN ===")
        print("1. Tambah Reservasi")
        print("2. Hapus Reservasi")
        print("3. Tampilkan Semua Meja")
        print("4. Jumlah Reservasi")
        print("5. Meja Selanjutnya")
        print("6. Meja Sebelumnya")
        print("7. Keluar")

        try:
            pilih = int(input("Pilih: "))
        except ValueError:
            print("Input tidak valid!")
            continue

        if pilih == 1:
            try:
                nomor = int(
                    input("Masukkan nomor meja: ")
                )

                bst.insert(nomor)

                print(
                    f"Meja {nomor} "
                    f"berhasil direservasi"
                )

            except ValueError:
                print("Input tidak valid!")

        elif pilih == 2:
            try:
                nomor = int(
                    input("Hapus reservasi meja: ")
                )

                bst.delete(nomor)

                print(
                    f"Reservasi meja {nomor} "
                    f"berhasil dihapus"
                )

            except ValueError:
                print("Input tidak valid!")

        elif pilih == 3:
            print("\nDaftar Meja:")
            bst.tampilkan_meja(bst.root)

        elif pilih == 4:
            print(
                f"Jumlah reservasi: "
                f"{bst.jumlah_meja(bst.root)}"
            )

        elif pilih == 5:
            try:
                nomor = int(
                    input(
                        "Cari meja selanjutnya dari: "
                    )
                )

                ans, found = bst.find_successor(
                    bst.root,
                    nomor
                )

                if found:
                    print(
                        f"Meja selanjutnya: {ans}"
                    )
                else:
                    print(
                        "Tidak ada meja selanjutnya"
                    )

            except ValueError:
                print("Input tidak valid!")

        elif pilih == 6:
            try:
                nomor = int(
                    input(
                        "Cari meja sebelumnya dari: "
                    )
                )

                ans, found = bst.find_predecessor(
                    bst.root,
                    nomor
                )

                if found:
                    print(
                        f"Meja sebelumnya: {ans}"
                    )
                else:
                    print(
                        "Tidak ada meja sebelumnya"
                    )

            except ValueError:
                print("Input tidak valid!")

        elif pilih == 7:
            print("Program selesai.")

        else:
            print("Pilihan tidak valid!")


if __name__ == "__main__":
    main()