# -*- coding: utf-8 -*-
"""tugas_akhir_judul3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rLoIOgLnX2rd8mKqBDzks0c1hY7uXcYN
"""

def sequential_search(data, n, target):
    i = 0
    counter = 0
    while i < n:
        if data[i] == target:
            counter += 1
        i += 1
    return counter

def main():
    # Daftar member gym
    data = ["Andi", "Budi", "Citra", "Denis", "Andi", "Fajar", "Budi"]

    n = len(data)

    print("Daftar Member Gym:", data)

    while True:
        target = input("Masukkan nama member yang ingin dicari: ").capitalize()

        if target.isalpha():
            break
        else:
            print("Input tidak valid, silakan masukkan nama!")

    counter = sequential_search(data, n, target)

    if counter > 0:
        print(f"Member bernama {target} ditemukan sebanyak {counter} kali.")
    else:
        print(f"Member bernama {target} tidak ditemukan.")

if __name__ == "__main__":
    main()
