# -*- coding: utf-8 -*-
"""tugas_akhir_judul2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15zHWyfqhfWMWaRzBy8mek3lTkLVy38ll
"""

def insertion_sort(arr, n):
    for i in range(1, n):
        temp = arr[i]
        j = i - 1

        while j >= 0 and arr[j] > temp:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = temp


def main():
    try:
        n = int(input("Masukkan jumlah mahasiswa: "))
    except ValueError:
        print("Input tidak valid")
        return

    arr = []
    print("Masukkan ukuran sepatu mahasiswa:")

    for i in range(n):
        while True:
            try:
                ukuran = int(input())
                arr.append(ukuran)
                break
            except ValueError:
                print("Input tidak valid, silakan masukkan angka!")

    print(f"Array sebelum diurutkan: {arr}")
    insertion_sort(arr, n)
    print("Array setelah diurutkan (Insertion Sort):", end=" ")
    for i in range(n):
        print(arr[i], end=" ")
    print()


if __name__ == "__main__":
    main()
