# -*- coding: utf-8 -*-
"""tugas_akhir_judul6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zc92bTwRfKKovqoqijn-K1EaPivsvY6w
"""

class Node:
    def __init__(self, key, judul, status):
        self.key = key
        self.judul = judul
        self.status = status  # tersedia / dipinjam
        self.next = None


class PerpustakaanHashMap:
    def __init__(self, size=10):
        self.SIZE = size
        self.table = [None] * self.SIZE

    def hash_function(self, key):
        return (key % self.SIZE + self.SIZE) % self.SIZE

    def insert(self, key, judul, status="tersedia"):
        index = self.hash_function(key)
        current = self.table[index]

        # update kalau key sudah ada
        while current is not None:
            if current.key == key:
                current.judul = judul
                current.status = status
                return
            current = current.next

        # insert baru di depan
        new_node = Node(key, judul, status)
        new_node.next = self.table[index]
        self.table[index] = new_node

    def search(self, key):
        index = self.hash_function(key)
        current = self.table[index]

        while current is not None:
            if current.key == key:
                return current
            current = current.next
        return None

    def remove(self, key):
        index = self.hash_function(key)
        current = self.table[index]
        prev = None

        while current is not None:
            if current.key == key:
                if prev is None:
                    self.table[index] = current.next
                else:
                    prev.next = current.next
                return True
            prev = current
            current = current.next

        return False

    def display(self):
        print("\nIsi Data Perpustakaan (Separate Chaining):")
        for i in range(self.SIZE):
            print(f"{i}: ", end="")
            current = self.table[i]
            while current is not None:
                print(f"({current.key}, {current.judul}, {current.status}) -> ", end="")
                current = current.next
            print("Kosong")


def main():
    perpustakaan = PerpustakaanHashMap()

    perpustakaan.insert(1, "Laskar Pelangi", "tersedia")
    perpustakaan.insert(11, "Bumi", "dipinjam")
    perpustakaan.insert(21, "Negeri 5 Menara", "tersedia")
    perpustakaan.insert(2, "Dilan 1990", "tersedia")

    perpustakaan.display()

    hasil = perpustakaan.search(11)
    if hasil is not None:
        print(f"\nBuku ditemukan: {hasil.judul} ({hasil.status})")
    else:
        print("\nBuku tidak ditemukan")

    perpustakaan.remove(11)
    print("\nSetelah menghapus buku ID 11:")
    perpustakaan.display()


if __name__ == "__main__":
    main()
